### ISSUE TITLE
SD option

### ISSUE THREAD

**Issue by 8eS3rz4sDu8oUx4q39hhv8o2k2e72dkb** [TerAnYu/mikrotik_ftp_backup#1]
Is it possible to save all that backups on disk/sd inside Mikrotik instead of FTP?

**Comment by TerAnYu** [comment]
Of course, comment out or delete lines: 33 to 44 and 5 to 8

**Comment by TerAnYu** [comment]
Project update.
You can now use tmpfs to store temporary files (requires ROS 7.7+) or store on external drives (need to remove lines 68 to 72).
